### ISSUE TITLE
Beskeder – knap til tilføj link virker ikke

### ISSUE THREAD

**Issue by nsturis** [AlternativetIT/alleos-issues#14]
Hvilken knap? Der er ikke nogen knap til at tilføje link - hvis der menes papirsklips-ikonet er det til vedhæftning og det virker måske ikke på mobilen

**Comment by karenmariaslente** [comment]
Det er papirklips-ikonet, jeg refererer til. Og det er på en Ipad, at det ikke virker. Vil gerne kunne tilføje filer på Ipad.

**Comment by huulbaek** [comment]
Ok, ja, ikonet eksisterer ikke der. Jeg kan i min vildeste fantasi ikke forestille mig, at nogen bruger iPads på den måde, men jeg tilføjer ikonet.

**Comment by huulbaek** [comment]
Løst i https://github.com/AlternativetIT/alleos-web-client/commit/a979eee685fd47f0997fe20807c5feb0fd7e3624
