### ISSUE TITLE
Samtale funktion i AlleOs

### ISSUE THREAD

**Issue by Faymaryhuish** [AlternativetIT/alleos-issues#22]
Altså der er nogle problemer med samtale funktionen i AlleOs. Yula og jeg har oplevet at den måde det vises på til højre e.g. når man bruger break osv. ikke fungerer når man så sender beskeden. 

Jeg fik skrevet dette ned da hun fortalte det "Tvunget linje skift virker ikke (hverken 
 eller return osv) - i “besked systemet” - hvis markdown bruges e.g. space space return eller 
 eller <br/>" <--- Intet virkede :( 
 
<img width="1273" alt="Screenshot 2019-04-04 at 13 12 18" src="https://user-images.githubusercontent.com/48998421/55552568-fe8e2380-56dd-11e9-962e-e97e0349ff1c.png">

**Comment by huulbaek** [comment]
Løst i https://github.com/AlternativetIT/AlleOs-Backend/commit/04248c1bac39eed1d40199551a31acc4f6614dfe
