### ISSUE TITLE
Ny titel - Uffes Nyhedsbrev => Nyt fra Folketingsgruppen

### ISSUE THREAD

**Issue by karenmariaslente** [AlternativetIT/alleos-issues#44]
Uffes nyhedsbrev skal skifte navn til Nyt fra Folketingsgruppen
Tilføj lille tekst under knappen, der siger:
Find alle nyhedsbreve fra Alternativets Folketingsgruppe 
Samme link

**Comment by huulbaek** [comment]
@nsturis done
