### ISSUE TITLE
Problemer med redigering og se teams i Safari

### ISSUE THREAD

**Issue by nsturis** [AlternativetIT/alleos-issues#5]
En del oplever problemer med redigering og at se teams, når de bruger safari

**Comment by nsturis** [comment]
@huulbaek har testet med mange og ældre versioner af Safari, men kan ikke se nogen problemer. Er det på mobil, der menes?

**Comment by nsturis** [comment]
Der menes nok på mobilen og generelt både safari og andre mobilbrowsere.

**Comment by karenmariaslente** [comment]
Præcis - mobil og tablets safari. Vil I teste og så lukke issueet her, når I har testet?

**Comment by huulbaek** [comment]
Jeg lukker her efter test. Det er svært at redigere medlemmer på fx iPad, hvis man ikke roterer på langs. Member view fix i https://github.com/AlternativetIT/alleos-web-client/commit/9f16bec71e5f27730cfce0cebb3980cde3b9d341
