### ISSUE TITLE
Teams V2

### ISSUE THREAD

**Issue by nsturis** [AlternativetIT/alleos-issues#58]
Hey T

Nåede det først i dag - har lagt det op i 'teams-v2' branch i front- og backend. Ser frem til at se hvad dine superkræfter kan spotte :)

Kh
Noah

**Comment by huulbaek** [comment]
Top.

Hvad var det nu, jeg skulle kigge på? :)

**Comment by nsturis** [comment]
Jeg kan ikke få Teams::updateMembers til at virke
